function isValid = policy_boundary(state, boundaries)
    isValid = (state.x >= boundaries.x_min && state.x <= boundaries.x_max) && ...
              (state.y >= boundaries.y_min && state.y <= boundaries.y_max) && ...
              (state.z >= boundaries.z_min && state.z <= boundaries.z_max);
end
